In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB
import seaborn as sns
from sklearn.metrics import confusion_matrix

In [2]:
fil = pd.read_csv('fil1.csv')
fil.head(5)

age  gender  time_sleep  no_of_hrs  minutes_to_sleep  wake_up  day_sleep  \
0   20       1           1          1                 2        0          1   
1   20       0           1          2                 0        0          0   
2   20       0           1          1                 0        0          0   
3   20       2           2          2                 0        0          2   
4   17       0           0          2                 0        0          3   

   tracker  use_tv  sleep_alone  sep_sleep_place  comfort  perf  \
0        1       1            2                1        3     2   
1        0       0            0                2        2     1   
2        1       0            0                0        5     3   
3        1       1            0                1        5     1   
4        1       1            2                2        4     0   

   trouble_sleep  trouble_back_to_sleep  medication  routine  rate  
0              2                      3           3        1     3  
1              3                      3           3        2     4  
2              3                      3           3        0     4  
3              3                      3           3        1     4  
4              2                      1           2        0     4

In [3]:
cols =  fil.columns.values
X = fil[cols[:-1]]
print X.shape,X.head(5)
y = fil[cols[len(cols)-1:]]
print y.shape,y.head(5)

(134, 17)    age  gender  time_sleep  no_of_hrs  minutes_to_sleep  wake_up  day_sleep  \
0   20       1           1          1                 2        0          1   
1   20       0           1          2                 0        0          0   
2   20       0           1          1                 0        0          0   
3   20       2           2          2                 0        0          2   
4   17       0           0          2                 0        0          3   

   tracker  use_tv  sleep_alone  sep_sleep_place  comfort  perf  \
0        1       1            2                1        3     2   
1        0       0            0                2        2     1   
2        1       0            0                0        5     3   
3        1       1            0                1        5     1   
4        1       1            2                2        4     0   

   trouble_sleep  trouble_back_to_sleep  medication  routine  
0              2                      3          

In [4]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2, random_state=int(time.time()))

In [5]:
print X_train.shape,y_train.shape
print X_test.shape,y_test.shape

(107, 17) (107, 1)
(27, 17) (27, 1)


In [6]:
gnb = MultinomialNB()
gnb.fit(X_train,y_train)

/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [7]:
print gnb.score(X_test,y_test)

0.7037037037037037


In [8]:
y_pred = gnb.predict(X_test)

In [9]:
print confusion_matrix(y_pred,y_test)

[[ 0  0  0  0]
 [ 0  0  1  0]
 [ 1  2 14  1]
 [ 0  0  3  5]]


In [28]:
for i in range(0,len(y_pred)):
    print y_test.values[i],y_pred[i]

[4] 4
[3] 3
[2] 3
[3] 3
[3] 3
[3] 2
[3] 3
[4] 4
[3] 3
[4] 3
[3] 3
[3] 3
[3] 3
[4] 4
[3] 3
[3] 3
[3] 4
[3] 3
[3] 4
[3] 3
[3] 4
[4] 4
[2] 3
[1] 3
[3] 3
[3] 3
[4] 4
